<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>API_layer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="14.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore" Version="2.14.3" />
	</ItemGroup>

	<ItemGroup>
		<!-- MATCHAR DINA MAPPMNAMN MED MELLANSLAG -->
		<ProjectReference Include="..\Application_Layer\Application_Layer.csproj" />
		<ProjectReference Include="..\Domain layer\Domain_Layer.csproj" />
		<ProjectReference Include="..\Infrastructure layer\Infrastructure_Layer.csproj" />
	</ItemGroup>

</Project>